server:
  port: 8001
  servlet:
    context-path: /front

spring:
  application:
    name: gateway-front
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}
        register-enabled: false

  zipkin:
    base-url: http://localhost:9411

user:
  auth:
    skipUrls:
      - /**/login
      - /**/register
    crossDomains:
      - all

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 10000
  OkToRetryOnAllOperations: false
